### ISSUE TITLE
Unable to update show 

### ISSUE THREAD

**Issue by dirkronsmans** [romanvm/kodi.tvmaze.scrobbler#26] opened 2021-04-06 11:15 UTC
**Issue description:**
I'm trying to update the info for "The Falcon and Winter Soldier (2021), the interface show my selection of the show and then I get "an error occured, check logs"

**Kodi debug log:**
https://paste.kodi.tv/pujepakice.kodi

**Additional context**
worked fine before.. suddenly happens. Using Matrix

**Comment by romanvm** [comment] 2021-04-06 17:04
I'm closing this issue because it has nothing to do with this project. However, the issue is still valid for `metadata.tvmaze` scraper so please open this issue in the relevant project.

**Closed as completed by romanvm** 2021-04-06 17:04 UTC
